### ISSUE TITLE
Sending an entirely filled message closes the connection

### ISSUE THREAD

**Issue by furfnsfw** [ayunami2000/ayunpictojava#12]
Sending a message that is nearly entirely filled in closes the connection and prevents sending the message.
![Screenshot_6](https://github.com/ayunami2000/ayunpictojava/assets/62636423/97608f7d-8ad9-4239-b80b-10be7af2f3da)

Wondering if this is an intentional feature to prevent too much data from being sent at once/spam filter or just a simple oversight?

**Comment by Cuphead74832** [comment]
> Sending a message that is nearly entirely filled in closes the connection and prevents sending the message. ![Screenshot_6](https://private-user-images.githubusercontent.com/62636423/323535546-97608f7d-8ad9-4239-b80b-10be7af2f3da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNzU4ODYsIm5iZiI6MTcxNTI3NTU4NiwicGF0aCI6Ii82MjYzNjQyMy8zMjM1MzU1NDYtOTc2MDhmN2QtOGFkOS00MjM5LWI4MGItMTBiZTdhZjJmM2RhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDE3MjYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZmYyOGUwODkzMWYwMWFjZmE5NDMyMmNjNzBjZTk1NWU3MGU4NjVjMzVkNmFjMDY0ZDhmMDgxZTA1OGFiYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._mg44ENkQqMyg4EtHbbGTSt9ShW_xVw33k_7bwVOUdc)
> 
> Wondering if this is an intentional feature to prevent too much data from being sent at once/spam filter or just a simple oversight?

Happening on the public Server or are you hosting the Server in your machines?

**Comment by ayunami2000** [comment]
Intentional feature to prevent spam
