### ISSUE TITLE
[FEATURE REQUESTS] Say command and more...

### ISSUE THREAD

**Issue by Cuphead74832** [ayunami2000/ayunpictojava#14]
Say command feature request: This command Will allow you to say stuff as SERVER vía the command line of the one who is hosting It like Minecraft an example would be "say The Server will perform its daily maintance in 15 minutes" so It would be sended to all public and private chats also to proof its LEGIT the messages casted by SERVER will have a Rainbow changing text box and nobody else will be able to do that with their textbox.

Image DragNDrop:
You can dragN drop a supported image and Will be painted on black and White for you to SEND It. If the image IS not in a compatible scale It Will be asked if you either want to scale It or stretch It on the text box. Before sending you Will be able to modify the results and for mobile there Will be an upload image Button.

Save Button: There will be a download Button to save whats currently loaded on your textbox as an image.

Prebuilds? 
Maybe BUILDING the Server and putting It on the releases like some people do with their projects might make the Server more accesible.

**Comment by AMiiInTime0016** [comment]
i personally think that the first idea is a cool one but i'm not sure what it would be used for
second and third points are practically made irrelevant with the discord mirror and i'm not sure what exactly you mean by the fourth but that's just me not being a coding guy

**Comment by ayunami2000** [comment]
first one: good idea but ill probably do like i already do for server messages which is use [SERVER] which includes brackets which cannot be in usernames otherwise

second one: no because it breaks the spirit of pictochat. if you want this functionality use something like https://github.com/WarpRomo/pictochat-drawing-bot

third one: already a planned feature

fourth one: good idea will do next time i push

**Comment by Cuphead74832** [comment]
Extra idea: I am spanish, i could not failed to notice that there is not an option for a ES-ES keyboard so please add an option to switch between using en-us and es-es as i have an original DS and a DSi i can confirm there is an Ñ also please make the sounds change the original NDS plays one receiving sound while the DSI plays the current one.

**Comment by AMiiInTime0016** [comment]
The Ñ should work. Maybe if you don't type it out directly but even if you can't, you can always go to the menu on the left since all of the keyboards are on PCO, not just an English one. Also what do you mean exactly by the second one?

**Comment by Cuphead74832** [comment]
Nevermind forget about SFX. It would be cool to just be able to save-load messages to your textbox instantly like snapshots.

**Comment by Cuphead74832** [comment]
New idea: If the Server is NOT actively moderated a change on the settings file from false to true can add a pop-up message warning to warn people of the CONTENT on the public rooms and that there is private rooms to avoid this CONTENT and to click the checkmark saying "I understand the consequences of unmoderated rooms" before clicking okay

**Comment by Cuphead74832** [comment]
Another idea: A value on the settings file would allow to set true to enable RATELIMIT or false if you think your PC can handle spam or doing private testing. (Would be always true by default)

**Comment by ayunami2000** [comment]
Please do not spam comments. Closing in favor of making suggestions on the discord server instead. (You are spamming my email as well as the webhook for GitHub updates in the discord server)
