### ISSUE TITLE
QoL, front-end: Dynamically resize the web app on browser resize

### ISSUE THREAD

**Issue by quackbarc** [ayunami2000/ayunpictojava#15]
Hello, ayunami! Could it be done so that whenever the browser's viewport changes, the Pictochat app fits itself accordingly to it? I thought it'd be a bit convenient -- I usually have the website on F11 and I exit out of it a lot, so getting to see everything while I'm out of F11 without  needing to refresh or fullscreen back would be fairly nice.

It should be a matter of simply hooking `intScaling()` (from index.html) to a `window.addEventListener("resize")`! I could even do a simple PR about it if you wish.

**Comment by ayunami2000** [comment]
added and working, thank you for suggesting and looking into it!!
