### ISSUE TITLE
Instructions for self-hosting ?

### ISSUE THREAD

**Issue by creeper451** [ayunami2000/ayunpictojava#4]
I cloned this repo and I haven't been able to host it on my own could you add some instructions on how to self host like which web server you're using and how to disable the captcha functionality.
Thanks you.

**Comment by 8bitbunny** [comment]
i did a quick glance, and it seems the strength of this web app is based around cloudflare's security.
it is possible to remove it for say, a offline server self hosted, but will require work from what i quickly saw in the java files. mainly it uses a data element called "secret" which has to be removed all over the place, best option would be making a startup variable that does this upon launching.

i have no idea if the creator has intent to do this, or not, but i might give it a go and make a pull request if i succeed?

**Comment by ayunami2000** [comment]
Oops I forgot to reply. To disable captcha, simply leave the secret field
blank, and edit the index page to remove the captcha field, and then it
will work without captchas.
https://github.com/ayunami2000/ayunpictojava/blob/master/src/main/java/me/ayunami2000/ayunpictojava/Main.java#L809

**Comment by creeper451** [comment]
Alright 👍, but my main question is about getting simple instructions for noobies like myself on how to self-host on a Linux server.
Thank you.

**Comment by Kippykip** [comment]
I'd also like to know, I've been looking for an alternative chat client backup in case discord deletes my discord.
Would love to self host

**Comment by nico721GD** [comment]
i just created a pull request with a step by step tutorial on how to self host it, should get merged pretty soon

**Comment by creeper451** [comment]
Thanks! I was able to build and host it but I wasn't able to remove the captcha.

**Comment by nico721GD** [comment]
If you want to make the captcha work, you need to go to the settings.json to set it up.
To remove the captcha you need to modify index.html in the www folder, where exactly i cant tell you but this was said by ayun

**Comment by creeper451** [comment]
I removed the line "<script src="https://challenges.cloudflare.com/turnstile/v0/api.js" async defer></script>" and it removed the captcha but when I press the "PICTOCHAT ONLINE" button it doesn't do anything.

**Comment by creeper451** [comment]
@nico721GD could you make another pull request on how to remove the captcha just like  how you wrote it for the build instructions it 🙏 , I'm still new to these stuff.

**Comment by nico721GD** [comment]
@creeper451 om still currently learning on how to do it, once i figured it out i'll update the pull request. Still learning on how to remove the captcha, remove the kick timer and maybe even remove the limit of peoples in 1 room

**Comment by ayunami2000** [comment]
added details to the README, refer to it :D
