### ISSUE TITLE
Sound doesn't work on chromium based browsers

### ISSUE THREAD

**Issue by Kippykip** [ayunami2000/ayunpictojava#8]
I believe chromium browsers have always been fussy with sound and want someone to interact with the page prior to playing any SFX.
A workaround might be to add some kind of play button to the page, then loading the HTML5 app or whatever.

Here's the error in the chrome console, firefox is unaffected by this issue
![image_2024-03-05_012125361](https://github.com/ayunami2000/ayunpictojava/assets/33023808/c97a69fe-2f22-44e9-b566-d582f28a55a4)

**Comment by ayunami2000** [comment]
Sound works for me on multiple chromium-based browsers, can you get a video demo of it not working?

**Comment by Kippykip** [comment]
Ah I see... It's happening to me on Opera GX. Might do a recording tomorrow!

**Comment by nico721GD** [comment]
@Kippykip general word of advice, avoid as much as possible opera gx, they have a tendency to break lots of basic website utilities without counting their horrible history

**Comment by ayunami2000** [comment]
Should be fixed.
